[versions]

teavm = "0.16.0"
asm = "9.8"
junit-jupiter = "5.11.4"

[libraries]

teavm-core = { module = "org.teavm:teavm-core", version.ref = "teavm" }
teavm-classlib = { module = "org.teavm:teavm-classlib", version.ref = "teavm" }
teavm-tooling = { module = "org.teavm:teavm-tooling", version.ref = "teavm" }
teavm-jso-impl = { module = "org.teavm:teavm-jso-impl", version.ref = "teavm" }
teavm-jso = { module = "org.teavm:teavm-jso", version.ref = "teavm" }
teavm-jso-apis = { module = "org.teavm:teavm-jso-apis", version.ref = "teavm" }
teavm-interop = { module = "org.teavm:teavm-interop", version.ref = "teavm" }
teavm-platform = { module = "org.teavm:teavm-platform", version.ref = "teavm" }
asm-core = { module = "org.ow2.asm:asm", version.ref = "asm" }
teavm-browser-runner = { module = "org.teavm:teavm-browser-runner", version.ref = "teavm" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version = "3.1.4" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:1.11.4"
jzlib = "com.jcraft:jzlib:1.1.3"

[plugins]

teavm = { id = "org.teavm", version.ref = "teavm" }
teavm-library = { id = "org.teavm.library", version.ref = "teavm" }
download = { id = "de.undercouch.download", version = "5.6.0" }
nodejs = { id = "com.github.node-gradle.node", version = "7.1.0" }
gretty = { id = "org.gretty", version = "5.0.2" }
